spring.application.name=spring_project_2026

# Activation explicite de la console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuration de la source de données H2
spring.datasource.url=jdbc:h2:mem:testdb;
spring.datasource.driverClassName=org.h2.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update